services:
  oidc-auth:
    build: .
    container_name: oidc-auth-server
    ports:
      - "8000:8000"
    environment:
      DATABASE_PATH: /app/data/local.db
      NODE_ENV: production
      PORT: 8000
      ISSUER_BASE_URL: http://localhost:8000
      AUTH_SERVER_BASE_URL: http://localhost:8000
      ACCESS_TOKEN_TTL_SECONDS: 300
      REFRESH_TOKEN_TTL_SECONDS: 2592000
      AUTH_SESSION_TTL_SECONDS: 2592000
      AUTH_SESSION_COOKIE_NAME: autht_session
      COOKIE_SECURE: "false"
      CLIENT_PORT: 3000
      CLIENT_BASE_URL: http://localhost:3000
    volumes:
      - ./cert:/app/cert
      - sqlite_data:/app/data
    restart: unless-stopped

volumes:
  sqlite_data:
